# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DevTools' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  
  #快如闪电的轻量级网络通讯库
  pod 'AFNetworking', '~> 3.1.0'
  
  #网络图片
  pod 'SDWebImage', '~> 3.8.2'
  
  #简洁优雅的轻量级约束布局库
  pod 'Masonry', '~> 1.0.2'
  
  #小黑框文字提示
  pod 'Toast', '~> 3.0'

  # Pods for DevTools

end
